# Generated by Django 4.1.2 on 2022-11-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45)),
                ('destination', models.CharField(max_length=45)),
                ('accommodation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reduced_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('max_number_of_participants', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='tours.place')),
                ('type_of_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_category', to='tours.tourcategory')),
                ('unit_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='tours.price')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_adults', models.IntegerField()),
                ('amount_of_children', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tours.user')),
            ],
        ),
    ]
