# Generated by Django 4.1.2 on 2022-10-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('accommodation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reduced_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_of_participants', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tours.places')),
                ('type_of_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_tour', to='tours.typeoftour')),
                ('unit_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='tours.price')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_adults', models.IntegerField()),
                ('amount_of_children', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tour', models.IntegerField()), #TODO fix as foreign key
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tours.user')),
            ],
        ),
    ]
