# Generated by Django 4.1.2 on 2022-11-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_reservation_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type_of_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_tour', to='tours.tourcategory'),
        ),
        migrations.DeleteModel(
            name='TypeOfTour',
        ),
    ]
