# Generated by Django 4.1.2 on 2022-11-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_price_id_alter_reservation_id_alter_tour_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('destination',)},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('normal_price',)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('tour',)},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ('type_of_tour',)},
        ),
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
        migrations.AddField(
            model_name='reservation',
            name='dateOfReservation',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
