# Generated by Django 4.1.2 on 2022-11-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_place_options_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateOfReservation',
            field=models.DateTimeField(null=True),
        ),
    ]
