# Generated by Django 4.1.3 on 2022-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_reservation_dateofreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dateOfReservation',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
