# Generated by Django 4.1.2 on 2023-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_reservation_tour_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, unique=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='reduced_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, unique=True),
        ),
    ]
