# Generated by Django 4.1.2 on 2023-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_price_normal_price_alter_price_reduced_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='accommodation',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='destination',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
