# Generated by Django 4.1.2 on 2023-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_place_accommodation_alter_place_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='place',
            name='destination',
            field=models.CharField(max_length=45),
        ),
    ]
