# Generated by Django 4.1.3 on 2023-01-09 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reduced_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ('normal_price',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_of_participants', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('place', models.CharField(max_length=45)),
                ('unit_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.price')),
            ],
            options={
                'ordering': ('max_number_of_participants',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReservation', models.DateTimeField(auto_created=True, null=True)),
                ('amount_of_adults', models.IntegerField()),
                ('amount_of_children', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tour',),
            },
        ),
    ]
